#!/usr/bin/env python3
"""
build_singlefile.py — re-inline the site into one self-contained HTML file.

The site folder is the SOURCE OF TRUTH; the single-file dashboard is a build
product. This script walks index.html, swaps every <link rel=stylesheet> for an
inline <style> and every <script src> for an inline <script>, and writes the
result out. Nothing is minified or reordered, so the single file behaves exactly
like the site (same frozen logs, same engine, same load order).

Anything between <!--SF-STRIP-START--> and <!--SF-STRIP-END--> is dropped: the
single file is standalone, so site-only chrome (the page-2 link chip, which
would point at a file that isn't shipped alongside it) does not belong in it.

  usage:  python3 build_singlefile.py [output.html]
  default output: ../adeptio_paybill_live_dashboard.html
"""
import re, sys, pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT  = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / 'adeptio_paybill_live_dashboard.html'

LINK = re.compile(r'^[ \t]*<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*/?>[ \t]*$')
SCPT = re.compile(r'^[ \t]*<script[^>]*src="([^"]+)"[^>]*>\s*</script>[ \t]*$')
STRIP = re.compile(r'<!--SF-STRIP-START-->.*?<!--SF-STRIP-END-->', re.S)

def read(rel):
    p = (HERE / rel).resolve()
    if HERE not in p.parents:
        raise SystemExit('refusing to inline outside the site folder: %s' % rel)
    if not p.exists():
        raise SystemExit('missing asset: %s' % rel)
    txt = p.read_text()
    # an inline <script> ends at the first "</script" in its text — guard against it
    if re.search(r'</script', txt, re.I):
        raise SystemExit('%s contains a literal </script — cannot inline safely' % rel)
    return txt, p

src = (HERE / 'index.html').read_text()
src, nstripped = STRIP.subn('', src)          # drop site-only chrome

out, inlined = [], []
for line in src.split('\n'):
    m = LINK.match(line)
    if m:
        css, p = read(m.group(1))
        out += ['<style>', '/* inlined from %s */' % m.group(1), css.rstrip('\n'), '</style>']
        inlined.append((m.group(1), p.stat().st_size)); continue
    m = SCPT.match(line)
    if m:
        js, p = read(m.group(1))
        out += ['<script>', '/* inlined from %s */' % m.group(1), js.rstrip('\n'), '</script>']
        inlined.append((m.group(1), p.stat().st_size)); continue
    out.append(line)

html = '\n'.join(out)
html = html.replace(
    '<!-- markup + boot only. Styles, data and engine are separate files, all loaded\n'
    '     with plain <link>/<script src> so this opens straight off disk (file://). -->',
    '<!-- BUILD PRODUCT — generated by paybill_dashboard_site/build_singlefile.py.\n'
    '     Edit the site sources, not this file, then re-run the build. -->')
OUT.write_text(html)

if nstripped:
    print('  stripped %d site-only block%s (SF-STRIP)' % (nstripped, '' if nstripped == 1 else 's'))
for rel, sz in inlined:
    print('  inlined %-22s %8.1f KB' % (rel, sz / 1024))
print('wrote %s  (%.1f KB, %d lines)' % (OUT, OUT.stat().st_size / 1024, html.count('\n') + 1))
